// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChatGPTHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "ChatGPTHelper.f2040d4c-208a-4d8d-8b76-a3b822e8769e";
        public const string Name = "ChatGPTHelper";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "lori longiave";
        public const string Tags = "";
    }
}
